let number1 = Number(prompt("Please, choose the first number"));
let number2 = Number(prompt("Please, choose the second number"));
e1 = number1 + number2;
e2 = number1 - number2;
e3 = number1 * number2;
e4 = number1 / number2;
console.log("The result of adding "+number1+" and "+number2+" is: "+e1); 
console.log("The result of subtracting "+number2+" from "+number1+" is: "+e2); 
console.log(+number1+" times "+number2+" is: "+e3); 
console.log(+number1+" divided by "+number2+" is: "+e4); 
